// const getUser = async (func()): Promise<> => {
//     try {
//     func();
//     } catch (error: unknown) {
//     if (error instanceof AxiosError) {
//         throw new ErrorResponseException(error.response?.data?.message ?? 'Unhandled error')
//         .setErrorResponse(error.response);
//     }

//     throw error;
//     }
// }

export {};